//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProjectUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string District { get; set; }
        public string Street { get; set; }
        public string Description { get; set; }
        public int Size { get; set; }
        public int Price { get; set; }
        public Nullable<int> PictureId { get; set; }
        public int UserId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual User User { get; set; }
    }
}
